spring:
  datasource:
    url: jdbc:h2:file:./test
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true # SQL 출력
#        format_sql: true # 포매터 적용
#
#logging.level:
#  org.hibernate.type: trace # 쿼리 파라미터 출력