spring:
  jpa:
    show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  profiles: h2-mem
  datasource:
    url: jdbc:h2:mem:test

---
spring:
  profiles: h2-file
  datasource:
    url: jdbc:h2:file:./test
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
